#! /bin/sh

#wait until the processes have been shut down (just in case)
pgrep -x sxhkd > /dev/null || sxhkd &
#while pgrep -u $UID -x picom >/dev/null; do sleep 0.2; done
##AUTOSTART
#compositor
picom &
#set cursor
xsetroot -cursor_name left_ptr &
#Enable touchpad tap
xinput set-prop "ELAN0710:01 04F3:30ED Touchpad" "libinput Tapping Enabled" 1 &
#resol
xrandr --rate 144 &
#set wallpaper
feh --bg-fill ~/wallpaper.sxnkr/desktop.wall/nord-pattern.jpg &
#feh --bg-fill /home/sxnkr/wallpaper.sxnkr/desktop.wall/hunter.png &
#polybar
~/.config/polybar/launch.sh &
#NotificationDaemon
dunst &

##Configurations
bspc monitor -d 1 2 3 4 5 6 7 8 9
#external config
if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
        xrandr  --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1366x768 --rotate normal --right-of eDP-1 &
        bspc monitor HDMI-1-0 -d 0 &
fi

bspc config border_width         0.55
bspc config window_gap           12.5
bspc config split_ratio          0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle         true
bspc config single_monocle              false
bspc config focus_follows_pointer       true
bspc config remove_disable_monitors     true
bspc config merge_overlapping_monitors  true
##Window rules
# remove all rules first
bspc rule -r *:*
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=tiled
bspc rule -a sxiv state=floating
bspc rule -a "alacritty -e cmus" desktop=^8 state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a galculator state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Firewall state=tiled
bspc rule -a Screenkey manage=off
