#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#polybar
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII # IX X

bspc config border_width         0.55
bspc config window_gap           12.5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a alacritty -e cmus state=floating
bspc rule -a Screenkey manage=off 
