#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII # IX

bspc config border_width         0.55
bspc config window_gap           12.5
bspc config split_ratio          0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle         true
bspc config single_monocle              false
bspc config focus_follows_pointer       true
## Window rules ----------------------------------------------#
# remove all rules first
bspc rule -r *:*
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a alacritty -e cmus state=floating
bspc rule -a Screenkey manage=off
## AutoStart Ups ----------------------------------------------#
#set cursor
xsetroot -cursor_name left_ptr &
#Enable touchpad tap
xinput set-prop "ELAN0710:01 04F3:30ED Touchpad" "libinput Tapping Enabled" 1 &
#set wallpaper
feh --bg-fill /home/alvarez/wallpaper.sxnkr/nordic-wallpapers/Cpu-city.png  &
#compositor
picom &
#polybar
~/.config/polybar/launch.sh &
#NotificationDaemon
dunst &
#Clipboard 
greenclip daemon &
